### ISSUE TITLE
Suggestions on RPC

### ISSUE THREAD

**Issue by longfeiWan9** [Tommo-L/NEO3-Development-Guide#13]
1. Refactor each RPC API function

    - Refer to [getblockheader 方法](https://github.com/Tommo-L/NEO3-Development-Guide/blob/master/cn/RPC/api/getblockheader.md)

2. Add other RPC API provided in plugins
   - there are some API provided by plugins, please add them since they are important as well
   - if there is a params related to big endian or little endian, please clarify.

**Comment by Tommo-L** [comment]
1. format [done]
2. add RpcWallet plugin. [done]
