### ISSUE TITLE
Suggestions on Smart Contract

### ISSUE THREAD

**Issue by longfeiWan9** [Tommo-L/NEO3-Development-Guide#14]
针对合约的部分，有一些改进建议：

1. 原生合约的介绍
   - 原生合约每个方法的介绍，作用不大，建议移除。
   - 选取几个典型的方法（balanceOf, transfer, unClaimGas），提供调用的实例：包括合约内调用，以及工具调用。
2. 合约的调用
   - 关于合约的调用，目前写在两个地方，建议合并在一个地方，讲清楚两种调用的使用(合约里，SDK里，等等)
3. 互操作服务
   - 互操作服务使用下面的system和NEO，建议合并成一张表

**Comment by ZhangTao1596** [comment]
改动说明
* 介绍
  * 已删除
  * 已添加name，transfer，unClaimGas的具体用法
* 调用
  * 已合并
* 互操作
  * 有的介绍太长，之前合并为表格，效果不好。未修改。

**Comment by Tommo-L** [comment]
done
