### ISSUE TITLE
Suggestions on VM

### ISSUE THREAD

**Issue by longfeiWan9** [Tommo-L/NEO3-Development-Guide#15]
1. 指令集
    - 指令集可否做成一张表，便于浏览
    - 指令集下面的费用，目前是这样表示：3e-7 GAS。 可否和费用表统一？不过如果可以做成表格的形式，费用表就可以删除。
2. 费用
   - VM下有费用表，合约下也有费用表，两个表的关系是什么？可以在文档中阐述一下， 或者是syscall下面加个介绍和链接？

**Comment by ZhangTao1596** [comment]
改动情况：
* 指令集
  * 之前修改过，效果不好，未修改。
  * 已修改
* 费用
  *  已经在vm中SYSCALL添加说明与链接

**Comment by Tommo-L** [comment]
done
