### ISSUE TITLE
Comments

### ISSUE THREAD

**Issue by Celia18305** [Tommo-L/NEO3-Development-Guide#6]
每章节开头的的NEO3变更部分需要统一：

- 标题统一为：NEO3变更部分
- 去掉每句话开头的NEO3，统一成新增X，弃用了XX，更新了XX，等等

【交易】

- 交易的数据结构跟之前相比有变化，在变更部分没有提及
- “其中，OpcodeSet为指令集，为第i种指令的费用，为第i种指令在合约脚本中的个数。”- 中间漏了两个参数OpcodePrice和n
- “除IP地址和端口号外，Neo中所有变长的整数类型都使用小端存储。”- 使用小端序存储。
- 原先的九种交易类型没有描述了？- 

【智能合约】

- Manifest小节中，属性列表ABI下层的列表需要增加缩进
- “payable 表 明合约可以接受资产的转入。”多一个空格
- “执行合约调用时，会检查 Permission 中配置 的权限”多一个空格
- 新增触发器system需要在NEO3更新内容中说明
- “Native Contract”标题最好写成 原生合约（Native Contract）
- C#统一大写
- “例如，如果要通过来调用合约0x43cf98eddbe047e198a3e5d57006311442a0ca15的transfer方法：”要通过什么来调用？
- Neo.Transaction.GetWitnesses，Neo.Witness.GetVerificationScript，Neo.Account.IsStandard 三个表格中功能描述没写完： “获取交易中的？”
- 互操作服务接口的变化需要在前面变更部分说明

【NeoVM】

- 指令集下面有些小标题下带灰条，需删除
- 指令集以前是113个，现在173，新增的opcode可否在变更部分说的更具体点，比如新增哪些大类，链接。费用部分NEO3才写出来，也应该在前面变更部分提出，并附链接。

【钱包】
标题“私钥”下方第一句话“钥是一个随机生成的位于1和n之间的任何数字”应该是“私钥是一个。。。”

“明文：输入的密码（UTF-8格式）
盐：地址哈希
n：16384
r：8
p: 8
length: 64” - 盐是什么？

“地址”小节下的普通地址和多方签名地址用小标题，而不是列表更规范
“DB3文件”小节下的第一个表格，“是否必须”改为“是否必填”，与后面表格统一

**Comment by ZhangTao1596** [comment]
修改了，请确认。
